In [2]:
%pip install seaborn

Collecting seaborn
  Obtaining dependency information for seaborn from https://files.pythonhosted.org/packages/83/11/00d3c3dfc25ad54e731d91449895a79e4bf2384dc3ac01809010ba88f6d5/seaborn-0.13.2-py3-none-any.whl.metadata
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\projects\labinsight_ai\venv\lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in c:\projects\labinsight_ai\venv\lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\projects\labinsight_ai\venv\lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\projects\labinsight_ai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\projects\labinsight_ai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\projects\labinsight_ai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\projects\labinsight_ai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\projects\labinsight_ai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in c:\projects\labinsight_ai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\projects\labinsight_ai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\projects\labinsight_ai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\projects\labinsight_ai\venv\lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in c:\projects\labinsight_ai\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/294.9 kB ? eta -:--:--
   -------- ------------------------------ 61.4/294.9 kB 812.7 kB/s eta 0:00:01
   ---------------- ----------------------- 122.9/294.9 kB 1.0 MB/s eta 0:00:01
   ---------------------------------- ----- 256.0/294.9 kB 1.7 MB/s eta 0:00:01
   ---------------------------------- ----- 256.0/294.9 kB 1.7 MB/s eta 0:00:01
   ---------------------------------- ----- 256.0/294.9 kB 1.7 MB/s eta 0:00:01
   ---------------------------------- ----- 256.0/294.9 kB 1.7 MB/s eta 0:00:01
   -------------------------------------- 294.9/294.9 kB 909.5 kB/s eta 0:00:00
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import seaborn as sns
print("Seaborn installed successfully:", sns.__version__)

Seaborn installed successfully: 0.13.2

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

print("All libraries working!")

All libraries working!

In [3]:
diabetes = pd.read_csv("../data/raw/diabetes.csv")
kidney = pd.read_csv("../data/raw/kidney_disease.csv")
heart = pd.read_csv("../data/raw/heart_disease.csv")

print("Datasets loaded successfully!")

Datasets loaded successfully!

In [4]:
print("Diabetes:", diabetes.shape)
print("Kidney Disease:", kidney.shape)
print("Heart Disease:", heart.shape)

Diabetes: (768, 9)
Kidney Disease: (400, 26)
Heart Disease: (267, 45)

In [5]:
print("===== DIABETES =====")
display(diabetes.head())

print("===== KIDNEY DISEASE =====")
display(kidney.head())

print("===== HEART DISEASE =====")
display(heart.head())

===== DIABETES =====

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

===== KIDNEY DISEASE =====

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,class
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

===== HEART DISEASE =====

,1,2,3,4,5,6,7,8,9,10,...,36,37,38,39,40,41,42,43,44,45
0,59,52,70,67,73,66,72,61,58,52,...,56,62,56,72,62,74,74,64,67,1
1,72,62,69,67,78,82,74,65,69,63,...,71,63,60,69,73,67,71,56,58,1
2,71,62,70,64,67,64,79,65,70,69,...,70,66,65,64,55,61,41,51,46,1
3,69,71,70,78,61,63,67,65,59,59,...,61,66,65,72,73,68,68,59,63,1
4,70,66,61,66,61,58,69,69,72,68,...,69,70,66,70,64,60,55,49,41,1

In [6]:
print("===== DIABETES =====")
display(diabetes.head())

print("===== KIDNEY DISEASE =====")
display(kidney.head())

print("===== HEART DISEASE =====")
display(heart.head())

===== DIABETES =====

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

===== KIDNEY DISEASE =====

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,class
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

===== HEART DISEASE =====

,1,2,3,4,5,6,7,8,9,10,...,36,37,38,39,40,41,42,43,44,45
0,59,52,70,67,73,66,72,61,58,52,...,56,62,56,72,62,74,74,64,67,1
1,72,62,69,67,78,82,74,65,69,63,...,71,63,60,69,73,67,71,56,58,1
2,71,62,70,64,67,64,79,65,70,69,...,70,66,65,64,55,61,41,51,46,1
3,69,71,70,78,61,63,67,65,59,59,...,61,66,65,72,73,68,68,59,63,1
4,70,66,61,66,61,58,69,69,72,68,...,69,70,66,70,64,60,55,49,41,1

In [7]:
print("DIABETES COLUMNS:")
print(diabetes.columns.tolist())

print("\nKIDNEY COLUMNS:")
print(kidney.columns.tolist())

print("\nHEART COLUMNS:")
print(heart.columns.tolist())

DIABETES COLUMNS:
['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

KIDNEY COLUMNS:
['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class']

HEART COLUMNS:
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45']

In [8]:
print("===== DIABETES =====")
print(diabetes.dtypes)

print("\n===== KIDNEY =====")
print(kidney.dtypes)

print("\n===== HEART =====")
print(heart.dtypes)

===== DIABETES =====
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

===== KIDNEY =====
id         int64
age      float64
bp       float64
sg       float64
al       float64
su       float64
rbc          str
pc           str
pcc          str
ba           str
bgr      float64
bu       float64
sc       float64
sod      float64
pot      float64
hemo     float64
pcv          str
wc           str
rc           str
htn          str
dm           str
cad          str
appet        str
pe           str
ane          str
class        str
dtype: object

===== HEART =====
1     int64
2     int64
3     int64
4     int64
5     int64
6     int64
7     int64
8     int64
9     int64
10    int64
11    int64
12    int64
13    int64
14    int64
15    int64
16    int64
17    int64
18    int64
19    int64
20    int64
21    int64
22    int64
23    int64
24    int64
25    int64
26    int64
27    int64
28    int64
29    int64
30    int64
31    int64
32    int64
33    int64
34    int64
35    int64
36    int64
37    int64
38    int64
39    int64
40    int64
41    int64
42    int64
43    int64
44    int64
45    int64
dtype: object

In [9]:
print("===== DIABETES MISSING VALUES =====")
print(diabetes.isnull().sum())

print("\n===== KIDNEY MISSING VALUES =====")
print(kidney.isnull().sum())

print("\n===== HEART MISSING VALUES =====")
print(heart.isnull().sum())

===== DIABETES MISSING VALUES =====
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

===== KIDNEY MISSING VALUES =====
id         0
age        9
bp        12
sg        47
al        46
su        49
rbc      152
pc        65
pcc        4
ba         4
bgr       44
bu        19
sc        17
sod       87
pot       88
hemo      52
pcv       70
wc       105
rc       130
htn        2
dm         2
cad        2
appet      1
pe         1
ane        1
class      0
dtype: int64

===== HEART MISSING VALUES =====
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
dtype: int64

In [13]:
heart = pd.read_csv("../data/raw/heart_disease.csv")

print("Shape:", heart.shape)
print("Columns:", heart.columns.tolist())
display(heart.head())

Shape: (303, 14)
Columns: ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [14]:
print(heart.shape)
print(heart.columns.tolist())

(303, 14)
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']